### ISSUE TITLE
Add support for browser

### ISSUE THREAD

**Issue by am** [m0dch3n/vue-cli-plugin-cordova#1]
Is there any way to run browser as platform?

Thanks

**Comment by m0dch3n** [comment]
Hi, I've no experience with the browser platform, so I didn't add it.

What's the advantage having browser as a platform ? Is cordova browser like electron ? So you need this, to build an executable native app ? 

Or is it more like, to have limited cordova api features in the browser during development in the browser ? Can you then i.e. use sensors like the accelerometer etc ? Or only basic things like camera etc, which are supported by a computer browser ?

I looked at your commit, and for the dev part, I'm asking me, if can not simply serve the app, with vue cli serve, and just add cordova.js, and don't execute cordova run browser... 

Looking at the code from cordova, you linked, I think cordova run browser is not doing more... 

I'll try to investigate more in the browser platform afterwards...

**Comment by am** [comment]
Hi @m0dch3n,

Thank you for looking into this. For the most part I use the browser platform only for development, since it's easier for other to open the project and try it out (no android SDK or Xcode is required).

The support is quite limited and it depends also if the plugins you use support the platform. This is in fact something that should be also considered, that the plugins are loaded, otherwise some functionality won't work. 

I though about the same, that maybe making a few changes on the `yarn dev` could make this work. But I also like the idea of having the same level of abstraction, this mean that if cordova already tackles this problem with a platform why not add use it instead of creating another layer for this?

**Comment by m0dch3n** [comment]
Does the cordova browser platform also support hot reload like vue ? Currently, the way you solved the problem, the served page is from /src-cordova/www, so everytime, you are making changes to your vue app, you need do rebuild it and put it to cordova's www folder...

That's why I prefer more the way I do, but letting vue serve the app with hot reload etc, and simply add cordova.js, like I do for android and ios...

**Comment by am** [comment]
@m0dch3n It should be working since it uses the same server has in android. The hot-reload does not depend on the platform, since its the server trigger by vue-cli that has this functionality. 

I did test by the time I did the PR, but let me double check that it works as intended.

**Comment by m0dch3n** [comment]
I just tried hot-reload, and with cordova run browser, it didn't detect automatically the changes in src-cordova/www.

So I think, it's better, if we tweak vue serve to host the dev page, and add there cordova...

**Comment by m0dch3n** [comment]
I even needed to rerun cordova run browser, to detect my changes in the index.html file...
