### ISSUE TITLE
i got some problems with the Android apk installing

### ISSUE THREAD

**Issue by syifeng** [m0dch3n/vue-cli-plugin-cordova#105]
![image](https://user-images.githubusercontent.com/7510994/74920275-dfd47080-5406-11ea-9237-6d2cf9354ee3.png)

**Comment by syifeng** [comment]
I just code with the readme doc, nothing else. So why

**Comment by m0dch3n** [comment]
I don't understand you problem... If you can't install the apk, make sure the package name of the apk, is not already with a different signature, then you use, to sign your apk...
