### ISSUE TITLE
Add support for electron platform

### ISSUE THREAD

**Issue by Kukks** [m0dch3n/vue-cli-plugin-cordova#106]
Cordova supports electron as a platform. Would be cool to integrate it in here

**Comment by vesper8** [comment]
I've been using https://github.com/nklayman/vue-cli-plugin-electron-builder

Maybe I'm missing something but doesn't that already accomplish what you would want?

**Comment by Kukks** [comment]
I also currently use that but there are advantages to using just the cordova platform support:
* less dependencies in the src
* Cordova browser plugins work in electron( and you can still use electron apis)
* consolidated build tool for all platforms
