### ISSUE TITLE
Problem with backend connection in production

### ISSUE THREAD

**Issue by damianlluch** [m0dch3n/vue-cli-plugin-cordova#108]
Hi!! Thanks for the project, it has been a great help but it is happening to me that when I do the build for production, the app does not connect to the backend.
In development if it connects me well.

That could be happening?
thanks!

**Comment by m0dch3n** [comment]
I guess it's related to https... But can have a lot other reasons...

Try

````
npm run cordova-build-only-www-android
cd src-cordova
cordova build android --debug
````

Then connect via adb within Chrome Remote Devices to your webview

**Comment by m0dch3n** [comment]
https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by m0dch3n** [comment]
I close also this issue, because it's not plugin related problem

If I'm wrong, feel free, to reopen it
