### ISSUE TITLE
ip questions

### ISSUE THREAD

**Issue by ifredom** [m0dch3n/vue-cli-plugin-cordova#109]
when i run  `npm run cordova-serve-android`，I don't know how to solve this ip problem.

![image](https://user-images.githubusercontent.com/13759936/76395528-78309600-63b2-11ea-9229-659fd119ae51.png)

![image](https://user-images.githubusercontent.com/13759936/76395558-94ccce00-63b2-11ea-83fc-4e3427dd3952.png)

**Comment by m0dch3n** [comment]
https://github.com/m0dch3n/vue-cli-plugin-cordova/issues/43

the library I'm using, takes the wrong IP, take a look at the issue
