### ISSUE TITLE
Error with ios 

### ISSUE THREAD

**Issue by damianlluch** [m0dch3n/vue-cli-plugin-cordova#116]
Hi, thanks for your job.

I use your project in my app and in IOS I get this error.

** CLEAN SUCCEEDED **

note: Using new build system

** CLEAN SUCCEEDED **

 INFO  executing "cordova run ios" in folder /Users/damianlluch/Documents/work/fbase-app/src-cordova
Cannot read property 'attrib' of null

Any suggetions?

**Comment by m0dch3n** [comment]
no, sorry

I don't have a clue, I would consider asking this in the cordova community, because it's a cordova problem, when the command `cordova run ios` fails...
