### ISSUE TITLE
There are problems with packaging

### ISSUE THREAD

**Issue by luocong2016** [m0dch3n/vue-cli-plugin-cordova#117]
There are problems with packaging

**Comment by m0dch3n** [comment]
I need more information...

**Comment by luocong2016** [comment]
```
vue -V
@vue/cli 4.4.6

node -v
v12.16.3
```

```
# keytool  create
src-cordova
    |- test.jks
    |- build.json

// vue.config.js
module.exports = {
  publicPath: "",
  pluginOptions: {
    cordovaPath: "src-cordova"
  }
};
```

> npm run cordova-build-android

resulet:
       My picture is not shown.

**Comment by luocong2016** [comment]
project github:
https://github.com/ruiz-daniel/professors-crodova-vue

**Comment by m0dch3n** [comment]
Sorry, I don't have the time to check out your project and analyse your problem, with this information. I'll keep this ticket open 1 week. If nobody is able to help, I'll close it.

From the info I currently have, it can be related to the vue and webpack packaging, or cordova... In both ways, it's better to look in these communities to solve your problem.

**Comment by luocong2016** [comment]
How to reproduce.

Delete file
```
/src-cordova/platforms
/src-cordova/plugins
/public/cordova.js
```

> npm run cordova-prepare
