### ISSUE TITLE
ios simulator not open

### ISSUE THREAD

**Issue by yokins** [m0dch3n/vue-cli-plugin-cordova#118]
env:
- cordova-android: ^8.1.0
- cordova-ios: ^5.1.1
- cordova: 9.0.0 (cordova-lib@9.0.1)
- node: 6.14.4
- xcode: 11.5

issue:
when run `yarn cordova-serve-ios` or `yarn cordova-serve-android`, just build vue and start serve.
the simulator not open with no any warning message or error message.

**Comment by m0dch3n** [comment]
can try if `cordova run ios` inside `./src-cordova` is working and starting the IOS simulator ? If it's not starting, you should contact and see within the cordova community, why it's not working

**Comment by yokins** [comment]
in `./src-cordova` run `cordova run ios`, the simulator can start success.

**Comment by m0dch3n** [comment]
ok, can you check if `yarn cordova-serve-ios` is executing `cordova run ios`

**Comment by yokins** [comment]
just start vue serve, not run `cordova run ios`

**Comment by yokins** [comment]
resolved！just install `yarn`, I don't know why `yarn` has anything to do with this plugin.

**Comment by yokins** [comment]
@m0dch3n My mistake. I should have used NPM
