### ISSUE TITLE
No way to specify --mode to make use of ENV variables

### ISSUE THREAD

**Issue by JamieBradley** [m0dch3n/vue-cli-plugin-cordova#119]
I can't find any way to specify the --mode parameter to make use of ENV variables.

e.g.

npm run serve --mode myenv

loads the ENV variables found in .env.myenv which can then be accessed in vue via process.env.VUE_APP_MYVAR

This doesn't seem to be possible using by running npm run cordova-serve-browser --mode myenv for example

**Comment by m0dch3n** [comment]
normally this should work:

https://github.com/m0dch3n/vue-cli-plugin-cordova/blob/3b428c36ad1cae85501a478066ad433aa6d77f77/index.js#L347

can you please check the content of `args` ?

**Comment by JamieBradley** [comment]
Hi, sure!


I ran `npm run cordova-serve-browser --mode webfrance`

and args is:

```
args {
  _: [ 'webfrance' ],
  modern: false,
  report: false,
  'report-json': false,
  'inline-vue': false,
  watch: false,
  open: true,
  copy: false,
  https: false,
  verbose: false
}
```

**Comment by m0dch3n** [comment]
Can you also try with:

`npm run cordova-serve-browser -- --mode webfrance`

**Comment by JamieBradley** [comment]
Yup!

```
args {
  _: [],
  modern: false,
  report: false,
  'report-json': false,
  'inline-vue': false,
  watch: false,
  open: true,
  copy: false,
  https: false,
  verbose: false,
  mode: 'webfrance'
}

```

runs:

`vue-cli-service cordova-serve-browser "--mode" "webfrance"`

thank you very much for looking at this btw!

**Comment by m0dch3n** [comment]
No problem!

**Comment by JamieBradley** [comment]
Sorry, is this fixed now?

**Comment by JamieBradley** [comment]
Can we re-open this?

When I said "thank you very much for looking at this btw!"

I didn't mean that it was fixed, I just meant thank you for looking at it :)

**Comment by m0dch3n** [comment]
> Sorry, is this fixed now?
> 

-> 
````
args {
  _: [],
  modern: false,
  report: false,
  'report-json': false,
  'inline-vue': false,
  watch: false,
  open: true,
  copy: false,
  https: false,
  verbose: false,
  mode: 'webfrance'
}
````
your mode is `webfrance` by running `npm run cordova-serve-browser -- --mode webfrance`, so your problem should be solved...

**Comment by JamieBradley** [comment]
No, because it runs

`vue-cli-service cordova-serve-browser "--mode" "webfrance"`

which does not work.

it should run:

`vue-cli-service cordova-serve-browser --mode webfrance`
