### ISSUE TITLE
is there a way to generate an ipa in a single command? currently I need two build commands

### ISSUE THREAD

**Issue by vesper8** [m0dch3n/vue-cli-plugin-cordova#123]
I'm wondering if I'm doing something wrong.. after much tinkering I managed to create a signed IPA that I was able to submit to Apple but every time I want to update my IPA I have to run two build commands which takes a long time

First, from the root of the vue project I have to run `npm run cordova-build-ios`

And then, from the root of `src-cordova` I have to run `cordova build ios --release --device --buildConfig build.json`

Then this generates an .IPA file which I can submit to apple via Transporter

Just wondering if there's a way to run a single command. I'm confused why I need to run both commands here. If I only run the 2nd command then it doesn't include my latest changes to my vue app

Would love to hear about what flow you are using to build/update/submit

Many thanks

**Comment by codecat** [comment]
It looks like there's a difference between building while an iOS device is connected via USB and building when there's not. If there's an iOS device connected via USB, then `npm run cordova-build-ios` produces an ipa, otherwise it only produces an app.

Not sure why this behavior seems to be different for the emulator vs. device though.

**Comment by m0dch3n** [comment]
Currently it's not possible to add arguments to the cordova command as all the arguments are added to the vue cli command...

The only cordova argument which gets accepted currently is --target

https://github.com/m0dch3n/vue-cli-plugin-cordova/issues/26

Is a discussion about that...

If you want to build latest vue app to cordova, you can do `npm run cordova-build-only-www-ios`

**Comment by m0dch3n** [comment]
PS currently I don't generate a production version for ios for the app store, so I have never looked into the flow...
