### ISSUE TITLE
Android app shows blank white screen

### ISSUE THREAD

**Issue by midasdev711** [m0dch3n/vue-cli-plugin-cordova#125]
Hi, I followed the doc and created a simple vue project.

vue create test
vue add vue-cli-plugin-cordova
yarn cordova-prepare
yarn cordova-serve-android

It shows only blank screen.

For ios, I set https to false in vue.config.js and it works fine.
But it doesn't work at all on android.

It shows white screen for a while and then below error.

`The connection to the server was unsuccessful. (https://x.x.x.x:8080)`

Do you have any idea about it?

**Comment by tu6ge** [comment]
Hi @midasdev711 ,I met the same problem as you, how did you solve it ?

**Comment by midasdev711** [comment]
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:; connect-src 'self' ws:;">

**Comment by tu6ge** [comment]
@midasdev711 I revised it as you said , but the problem is still

**Comment by tu6ge** [comment]
I remove path `node_modules` , `platforms`, `plugin` in  `src-cordova`, and I try it , my problem is solved ,surprised
