### ISSUE TITLE
iOS Serves blank Page

### ISSUE THREAD

**Issue by tarsusi** [m0dch3n/vue-cli-plugin-cordova#126]
Hi,

I am creating a new project like this:

```
vue create cordova-app
cd cordova-app
vue add cordova(adding ios and android as platforms)
```

Then I try to serve iOS application by running this command:

```
npm run cordova-prepare
npm run cordova-serve-ios
```

It opens the default emulator but there is just a blank page shown.

```
vue --version
3.7.0

cordova --version     
10.0.0
```

Thanks.

**Comment by danielgottbehuet** [comment]
Same here. Just a blank (black) screen after config the xcode and run.

**Comment by luk156** [comment]
same here

**Comment by luk156** [comment]
For me the problem is the https,
i've set in vue.config.js

```
devServer: {
    https: false,
}
```
and now works
