### ISSUE TITLE
How to use cordova plugins?

### ISSUE THREAD

**Issue by nathantaal** [m0dch3n/vue-cli-plugin-cordova#127]
How can I use cordova plugins in the vue source?

**Comment by pslyman** [comment]
Did you figure this out? The docs say how to install plugins, but not how to use them. Regular imports don't seem effective.

**Comment by Aminerman** [comment]
Having the same issue here, if anyone has an answer it'd be great

**Comment by allanvb** [comment]
Did anyone figured out how to solve this problem ?

**Comment by pslyman** [comment]
Yeah, kind of. When you install Cordova plugins they're assigned to global objects/methods. The Vibrate plugin is a good example of this: https://cordova.apache.org/docs/en/10.x/reference/cordova-plugin-vibration/

You won't get type handling, and you may have to register the type in main.ts if it complains. 

Also keep in mind that plugins don't work until user interaction, as well as the deviceready event.

**Comment by allanvb** [comment]
@pslyman thank you for quick response. In your example you used kind of plugins that are "injected" to navigator.
I don't have problems with plugins that act this way.
I can't figure out how to use plugins that cannot be called through navigator.
For example I need to use [cordova-plugin-otp-autofill](https://www.npmjs.com/package/cordova-plugin-otp-autofill) in my project.

As of documentation I need to use smsOtpAutofill object to access plugin's features but I can't. This object is always undefined. I tried direct import in Vue component, tried call through cordova.plugins, tried to install package inside core's node_modules but nothing works.

**Comment by pslyman** [comment]
@allanvb Fair point. I'm using Auth0 Cordova (https://github.com/auth0/auth0-cordova) and you have to create your own object which calls the plugin. For example:
`var Auth0Cordova = require('@auth0/cordova');`

But the usecase may be different. That's how I've used it when the global object isn't already assigned. 

If that doesn't help, I can take another look at plugins I've dabbled with. I usually use Ionic, this is my first Cordova Vue project using this cordova-vue plugin, so I'm kinda figuring things out as I go.

**Comment by pslyman** [comment]
I'll also add that sometimes you have yo do `npm install` as well as `cordova plugin add <pluginName>`. One for Cordova, the other for Vue.

**Comment by allanvb** [comment]
@pslyman thank you a lot. I'll try it tomorrow and I'll return with feedback :)
