### ISSUE TITLE
Crash when using cordova-serve-android

### ISSUE THREAD

**Issue by MathisTLD** [m0dch3n/vue-cli-plugin-cordova#130]
https://github.com/m0dch3n/vue-cli-plugin-cordova/blob/86c0330f8c178a385f8712e3a8619f633cea1f1f/index.js#L43
should be replaced by:
```js
      cordovaConfigPathToUpdate = 'res/xml/config.xml'
```
when using cordova-android^6.4.0

**Comment by m0dch3n** [comment]
Is it not more simple to upgrade your cordova android to 9.x? 6.4 is quite old...

**Comment by MathisTLD** [comment]
Maybe... 
Team told me to use this particular version for compatibility reasons. Things might have changes now i'll see if everything works in v9. Thanks
