### ISSUE TITLE
Admin rights for windows users

### ISSUE THREAD

**Issue by riksnelders** [m0dch3n/vue-cli-plugin-cordova#14]
Getting following error:

ERROR  No platforms installed in "path here\src-cordova"

Things that might be wrong:
folder is not created [ solved, run as administrator on windows]
platforms are not added cause working directory not recognized as cordova based project

**Comment by m0dch3n** [comment]
I didn't test on windows, so your problem was solved by running the command as administrator on windows, because otherwise the folder is not created?

**Comment by m0dch3n** [comment]
If you have choosen "src-cordova" as path, you get this error, when src-cordova/platforms/android i.e doesn't exist...

Nevertheless, can you please copy paste me your console, when you do "vue add cordova" so I can see, if there is any special error message...

**Comment by riksnelders** [comment]
Ran vue add cordova in root project folder.
Next to that, folder is created, but the platforms i selected are not added. thats the culprit.
![image](https://user-images.githubusercontent.com/15074808/46143181-80961f00-c259-11e8-9210-5043b0587737.png)

**Comment by riksnelders** [comment]
Think i found the problem. If i run bash in my terminal, administrator rights are gone it seems.
Ran it normally then platforms get added

**Comment by m0dch3n** [comment]
currently I don't have windows, so I can't try by myself...

Nevertheless, please try the following steps:

* remove src-cordova folder
* run `cordova create src-cordova com.vue.example.app`
* cd src-cordova
* run `cordova platform add android`

Paste me the outputs here

**Comment by m0dch3n** [comment]
Then 
* cd ..
* `npm run cordova-serve-android`

Should work...

**Comment by m0dch3n** [comment]
> Think i found the problem. If i run bash in my terminal, administrator rights are gone it seems.
> Ran it normally then platforms get added

Try in your bash, the cordova commands, maybe they need administrator rights...

**Comment by riksnelders** [comment]
Yes this does work!

Its the creating.. I ran as admin, with and without bash. Not all the files are being created. cuz platforms is empty now. but theres a platform folder.

**Comment by m0dch3n** [comment]
> Yes this does work!
> 
> Its the creating.. I ran as admin, with and without bash. Not all the files are being created. cuz platforms is empty now. but theres a platform folder.

ok, can you please try manually the steps above, and paste the outputs...

**Comment by riksnelders** [comment]
![image](https://user-images.githubusercontent.com/15074808/46144220-92c58c80-c25c-11e8-8e63-59ce1891dd42.png)

**Comment by m0dch3n** [comment]
Interesting, it seems the administrator right problems, do not exist, if you run the commands manually...

As I said, I currently can't try on windows by myself, but maybe, you can the solve the problem, just:

* checkout the project
* in a fresh vue cli app, run npm install --save-dev file://path/to/plugin
* vue invoke cordova

This will invoke generator.js which itselfs executes the cordova commands...

To have more outout about the command, take a look in index.js

````
{
      cwd: srcCordovaPath,
      env: process.env,
      stdio: 'inherit', // pipe to console
      encoding: 'utf-8'
    })
````

**Comment by riksnelders** [comment]
So far, the serve-android is not working.. the build version is working

**Comment by m0dch3n** [comment]
I replaced node's spawn with cross-spawn https://www.npmjs.com/package/cross-spawn

This should solve the admin and folder creation issues...

Can you please retry with 2.0.5 ?

**Comment by riksnelders** [comment]
Hey. I just checked the serve-android. 
Its routing to the https:// version.
So i need to be on local network with my deviece.
If run from terminal it goes straight to app.

Havent got time to check the full install. but Im guessing, since the serve actually runs it works: )

**Comment by m0dch3n** [comment]
> Hey. I just checked the serve-android.
> Its routing to the https:// version.
> So i need to be on local network with my device. and its not showing the actually APP
> If run from terminal it goes straight to app.
> 
> Havent got time to check the full install. but Im guessing, since the serve actually runs it works: )

very strange, on my machine it didn't use https and the serve command command should also ignore https, if you have this setting somewhere in your vue.config.js or .env, because I'm overriding it...

https://github.com/m0dch3n/vue-cli-plugin-cordova/blob/ead4fb181053d3f0167d44076b7467e5f6a3a67e/index.js#L132

**Comment by riksnelders** [comment]
Everything seems to be working now :)
