### ISSUE TITLE
Cant install the app-release-unsigned.apk

### ISSUE THREAD

**Issue by aglopes-monitar** [m0dch3n/vue-cli-plugin-cordova#16]
Created new and clean build.

donne 0 coding just the default cli template
1) 'npm run cordova-build-android' -> 'cli project folder'
2) cordova build android --release  -> 'inside src-cordova folder'
3) after download apk in cellphone; 
gave permissions and it didnt install

**Comment by aglopes-monitar** [comment]
Can open the scr-codova/plataforms/android
In android studio, and run on device... i can allways sign the apk.

**Comment by m0dch3n** [comment]
Did you read the README ? There is no need to execute `cordova build android --release`

**In Production mode**
Adding cordova.js to your index.html
Defining process.env.CORDOVA_PLATFORM to android, ios or browser
Pointing the cordova config.xml to index.html
Building the app, output to /cordovaPath/www
Executing 'cordova clean'
Executing 'cordova build platform --release'
**Please note**
You **need to manually sign** and publish the app in the app store

Please google for jarsign and zipalign an android release apk

Once you have jarsigned and zipaligned your apk, you can run adb install nameofapp.apk

**Comment by m0dch3n** [comment]
https://developer.android.com/studio/publish/app-signing

**Comment by m0dch3n** [comment]
c.f. Sign your app manually from the command line

**Comment by aglopes-monitar** [comment]
Nice thanks

m0dch3n <notifications@github.com> escreveu no dia terça, 2/10/2018 à(s)
10:55:
