### ISSUE TITLE
`cordova plugin remove [plugin]` doesn't always work

### ISSUE THREAD

**Issue by humblecoder** [m0dch3n/vue-cli-plugin-cordova#23]
Recently, specifically, I've attempted using a few plugins that, after build, will not remove.  The script will claim to remove them, then end with something like:

```
Uninstalling 1 dependent plugins.
Uninstalling cordova-plugin-compat from android
Android Studio project detected
Uninstalling phonegap-plugin-speech-recognition from android
Uninstalling 1 dependent plugins.
Uninstalling cordova-plugin-compat from browser
Uninstalling phonegap-plugin-speech-recognition from browser
js-module uninstall called : plugins/phonegap-plugin-speech-recognition/www/browser/SpeechRecognition.js
Uninstalling 1 dependent plugins.
Uninstalling cordova-plugin-compat from ios
ENOENT: no such file or directory, open '/Users/myuser/code/cordova_projects/myproject/src-cordova/platforms/ios/www/cordova_plugins.js'
```

This happens with various plugins.  The only solution ends up being to `cordova platform remove` and re-add the platform.  Please advise.

**Comment by m0dch3n** [comment]
Sorry, but I think this is more cordova related, so please ask this in the cordova community...

When you run cordova-serve-* or cordova-build-*, the vue cordova plugin basically only runs some cordova commands

**Comment by humblecoder** [comment]
Ha! I actually figured as much in my original posting, but I removed it and posted anyway.  Will do, thanks.
