### ISSUE TITLE
.env not loaded

### ISSUE THREAD

**Issue by valh1996** [m0dch3n/vue-cli-plugin-cordova#24]
Hello, is it normal that my".env" file at the root of my project is not loaded?

I would like these variables regardless of mode and platform.

Contents of the .env:
```
VUE_APP_API_ENDPOINT=http:/127.0.0.1:3333
```

`process.env` returns:
```
{
  NODE_ENV: "development",
  BASE_URL: "",
  CORDOVA_PLATFORM: "browser"
}
```

VueCLI version:  ^3.0.4

**_Documentation_**: https://cli.vuejs.org/guide/mode-and-env.html

Thank you in advance for your help!

**Comment by m0dch3n** [comment]
Which plugin version do you use ? With 2.0.8 everything is working fine... PS My vue cli version is 3.0.5
