### ISSUE TITLE
Devserver and CORS

### ISSUE THREAD

**Issue by Blackfaded** [m0dch3n/vue-cli-plugin-cordova#25]
I am facing an issue when developing with the android dev server with ```npm start cordova-serve-android```.
The problem is that I cannot access domains other than my devserver hostsystem.
When I want to access other domains which do not have ```access-controll-allow-origin: *``` enabled the requests ends with cors issues. When my App is build and running on device or simulator everything is working perfectly, because in that case the request is send from the **file** index.html and not the localhost **devserver**.

How can I solve this problem? I cannot enable cors on the requested server.

**Comment by m0dch3n** [comment]
Have you tried this?

https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/

**Comment by Blackfaded** [comment]
Yes, but it does not work either.

Thats my config.xml:
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.vue.example.app" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>VueExampleAppName</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="http://192.168.178.26:8080" />
    <allow-navigation href="http://192.168.178.26:8080" />
    <allow-navigation href="*" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <engine name="android" spec="^7.1.1" />
    <engine name="browser" spec="^5.0.4" />
</widget>
```

**Comment by m0dch3n** [comment]
When you execute `npm run serve` you don't encounter this problem? Because the webview in the cordova app is only a browser, so you should also encounter your cors issue with `npm run serve`... 

Have you looked in chrome devtools, in the remote device section? Maybe you can also try a different emulator with a different android version... The standard webview of android 4.0 is very old i.e.

Or look at this https://cli.vuejs.org/config/#crossorigin

Sorry, can't help you more here...
