### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by Blackfaded** [m0dch3n/vue-cli-plugin-cordova#27]
When I set 
```
devServer: {
    https: true   
}
```
in vue.config.js the url in config.xml does still get set to http

**Comment by m0dch3n** [comment]
If you run `npm run serve` it should be https, for `npm run cordova-serve*` you have the problem, that the cordova webview on your phone does not trust your connection, so everything needs to be http, unless you install the root cert, of your devserver on the phone

**Comment by m0dch3n** [comment]
https://github.com/m0dch3n/vue-cli-plugin-cordova/blob/7fd827b9a0e1dea5515f84c283ab0c481d322bb1/index.js#L135

**Comment by m0dch3n** [comment]
@Blackfaded Did this answer your question enough ?
