### ISSUE TITLE
cordova-serve-android is not working

### ISSUE THREAD

**Issue by odai-alali** [m0dch3n/vue-cli-plugin-cordova#28]
I tried with a fresh install but the cordova webview is unable to access the dev server ip.

Turning the firewall off did not help. `vue-cli-service cordova-serve-android --host 0.0.0.0` did not help neither.

Any idea?

**Comment by m0dch3n** [comment]
Try to open it on a normal browser on the device, both need to be in same network... If the browser works, check that the cordova config.xml is pointing to your devserver

**Comment by odai-alali** [comment]
I found the problem. The script somehow picked the wrong IP (the IP of the `NAT`  virtual network)

I had to run `.\node_modules\.bin\vue-cli-service cordova-serve-android --public <my local ip>:8080` to get it working

Thanks

**Comment by m0dch3n** [comment]
No problem, I used (this)[https://www.npmjs.com/package/address] library, to determine your ip, maybe the lib is not able to determine your ip...

**Comment by omkardusane** [comment]
it by default takes the IP on the first network switch found on the device, which should not happen, 
```vue-cli-service serve```  is able to detect correct IP

**Comment by omkardusane** [comment]
are you planning to fix this ?
