### ISSUE TITLE
implement a service worker?

### ISSUE THREAD

**Issue by micardona96** [m0dch3n/vue-cli-plugin-cordova#30]
Excellent complement thanks for sharing,
I am working on a web application that uses a service worker to cache the "run time" images in the local storage, and now I create the "mobile application", but when implementing the cordova add-on, the service worker It does not work because the images are always downloading again, it must be by the https, what could I do?
Greetings from Colombia, forgive my English.

**Comment by m0dch3n** [comment]
My internet search is saying the same:

https://stackoverflow.com/questions/44877656/how-to-use-service-workers-in-cordova-android-app

IOS seems to not support Service workers:

https://hollyschinsky.github.io/todos-app-pwa/lesson6.html

So in short, service workers were made to add functionalities, to browsers and not for native or hybrid apps IMO
