### ISSUE TITLE
CORDOVA_PLATORM undefined

### ISSUE THREAD

**Issue by martinglover** [m0dch3n/vue-cli-plugin-cordova#31]
In `vue.config.js` `CORDOVA_PLATFORM` is undefined so I am unable to check when defining the baseUrl

`baseUrl: (process.env.CORDOVA_PLATFORM && process.env.CORDOVA_PLATFORM !== 'browser') ? '' : '/',`

Is there a better way other than defining on the package.json scripts as this is duplication of definition?
`"cordova-build-android": "CORDOVA_PLATFORM=android vue-cli-service cordova-build-android",`

**Comment by m0dch3n** [comment]
I think vue is loading vue.config.js before it's loading/executing the plugins, so this is not possible with a plugin...

**Comment by m0dch3n** [comment]
Just tried this out, vue.config.js is defined before the plugin is defined, so I'm unable to define process.env.CORDOVA_PLATFORM in the plugin before vue.config.js is defined... One possible solution so would be your idea, to define this in package.json

**Comment by jacobg** [comment]
Why don't you just check `process.env.npm_lifecycle_event` to see the npm command you're running?
i.e., `const isAndroid == process.env.npm_lifecycle_event.includes('android')`
