### ISSUE TITLE
customizing index.html

### ISSUE THREAD

**Issue by jacobg** [m0dch3n/vue-cli-plugin-cordova#32]
Firstly, nice project!

I see that index.html is added to .gitignore. Is it wrong to not ignore it, and edit it to add stuff? I think it's a support feature in Cordova, so just making sure the plugin is friendly with that, or if it might cause a problem?

**Comment by jacobg** [comment]
Oh never mind, I didn't noticed public/index.html.

**Comment by m0dch3n** [comment]
JFYI the cotdova plugin does not add index.html or public/index.html to .gitignore

So, maybe you have another plugin or this entry comes from something else...
