### ISSUE TITLE
command line build/serve ios/android

### ISSUE THREAD

**Issue by jacobg** [m0dch3n/vue-cli-plugin-cordova#33]
I'm able to run cordova-serve-browser. But cordova-serve-ios, cordova-serve-android, cordova-build-ios, and cordova-build-android all fail. See errors below. But the build does get far enough to generate the platform file so that I can open the xcworkspace file in Xcode and gradle project in Android Studio, and then manually build and run it.

Also I needed to install the following:
- `brew install gradle`
- `npm install ios-deploy -g`

The iOS error is:
```
 INFO  executing "cordova build ios --release" in folder /Users/jacob/workspace/fc-tc-vue/src-cordova
Building project: /Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/ios/fc.xcworkspace
	Configuration: Release
	Platform: device
User defaults from command line:
    IDEArchivePathOverride = /Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/ios/fc.xcarchive

Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/ios/build/device
    SHARED_PRECOMPS_DIR = /Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/ios/cordova/build-release.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Distribution
    ENABLE_BITCODE = NO
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

error: archive not found at path '/Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/ios/fc.xcarchive'
** EXPORT FAILED **

CordovaError: Promise rejected with non-error: 'Error code 65 for command: xcodebuild with args: -exportArchive,-archivePath,fc.xcarchive,-exportOptionsPlist,/Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/ios/exportOptions.plist,-exportPath,/Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/ios/build/device'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Then Android error is:
```
 INFO  executing "cordova clean" in folder /Users/jacob/workspace/fc-tc-vue/src-cordova
Android Studio project detected
ANDROID_HOME=/Users/jacob/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
Subproject Path: CordovaLib
Subproject Path: app
/Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/android/gradlew: Command failed with exit code EACCES
 INFO  executing "cordova build android --release" in folder /Users/jacob/workspace/fc-tc-vue/src-cordova
Android Studio project detected
ANDROID_HOME=/Users/jacob/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
studio
Subproject Path: CordovaLib
Subproject Path: app
/Users/jacob/workspace/fc-tc-vue/src-cordova/platforms/android/gradlew: Command failed with exit code EACCES
```

Any ideas?

**Comment by m0dch3n** [comment]
Nope, sorry, and this issue tracker should only be used for plugin related problems.

Your problems are cordova and or permissions related, like EACCES in the android command.

If you never got `cordova run android` or `cordova run ios` to work before, or don't have enough experience with cordova, maybe you should try cordova first without vue, and by simply setting like say it their documentation:

https://cordova.apache.org/docs/en/latest/guide/cli/index.html

If you get this to work, this vue plugin should also work, because the in short the plugin is only putting the vue file in cordova's www folder and then executing the cordova commands...

**Comment by jacobg** [comment]
Actually, my last comment was not the solution. To fix the error about missing xcarchive file, I have to run cordova build with the command line argument:  `--buildFlag='-UseModernBuildSystem=0'`. I found this solution on StackOverflow:
https://stackoverflow.com/questions/52281848/cordova-build-ios-error-archive-not-found-at-path-path-to-myapp-xcarchive

Which brings my question to:  Should there be a way to specify command line arguments (or a build.json file) when calling `npm run cordova-build-*`?  Perhaps issue #26 is a place for that discussion.
