### ISSUE TITLE
can this work with fastlane and the fastlane cordova plugin?

### ISSUE THREAD

**Issue by vesper8** [m0dch3n/vue-cli-plugin-cordova#36]
I want to automate as much as possible the deployment process of my ios/android vue-cli apps and I think Fastlane is perfect for this. There's this cordova plugin here https://github.com/bamlab/fastlane-plugin-cordova that I'd like to use.

But reading the docs of Fastlane and of this plugin it looks like it's mostly meant to work with projects built with Android Studio / Xcode and I was wondering if you think or know if it's possible to use it with a regular vue-cli project in combination with your great plugin?

Right now I'm at the point where cordova-serve-android works but I get a white screen when trying to install the unsigned build produced by cordova-build-android

I believe that's because I need to sign it first, although I've read conflicting reports that I should be able to install it on my own device without signing it first (I'm only trying to install the built apk at this point, not yet ready to dabble with publishing it to an app store)

The signing process with Jarsigner and ZipAlight is quite confusing at this point so I thought I could make it a lot easier by letting Fastlane do the heavy lifting.. hence my question now

Hope you have some time to offer some guidance on this.. thanks much!

**Comment by m0dch3n** [comment]
I don't have any experience on fastlane, the plugin is simply creating a cordova project, then on serve its running vue cli serve, pointing config.xml to devserver, and executing cordova run...

on build, it's running vue cli build with output directory src-cordova/www and then cordova build

if you have a white page on build, make sure, all your paths etc work relatively, as there is no longer the web packed devserver, serving the files, but they are simply served from file://android_assets/www/

to better find out, what the problem on build is, run cordova-build-android, this will put the build to src-cordova/www, you can abort the execution when cordova build is executed, then cd to src-cordova and rerun cordova build android --debug, afterwards you can connect with Chrome remote devices to the webview of the app...
