### ISSUE TITLE
Info.plist file not found

### ISSUE THREAD

**Issue by evinkuraga** [m0dch3n/vue-cli-plugin-cordova#40]
Anyone else running into this issue when compiling for iOS:

```
Build settings from configuration file '/Users/me/code/myapp/src-cordova/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

/Users/me/code/myapp/src-cordova/platforms/ios/build/emulator/myapp.app/**Info.plist file not found.**
No target specified for emulator. Deploying to iPhone-X, 12.1 simulator
```

Then it gets suck on this forever.

**Comment by scottlilo** [comment]
I am getting the same error when running through vue-cli-service

Try navigating into your cordova directory (src-cordova), and building it with this flag

--buildFlag='-UseModernBuildSystem=0'

cordova run ios --buildFlag='-UseModernBuildSystem=0'

**Comment by m0dch3n** [comment]
you can use build.json for this

https://github.com/m0dch3n/vue-cli-plugin-cordova/issues?utf8=✓&q=is%3Aissue+build.+json

**Comment by tripflex** [comment]
I can confirm having this same issue as well .... @m0dch3n so is this a configuration specific issue for me and this other person, or what would be causing this problem?

**Comment by tripflex** [comment]
Found more details from here regarding using this build flag:
https://stackoverflow.com/questions/52584550/blank-app-fails-debug-build-info-plist-file-not-found

For some odd reason I had to run it with the `--target "iPhone-8"` flag first, and any subsequent calls worked thank you @scottlilo
