### ISSUE TITLE
serve-ios and build-ios encountering build error

### ISSUE THREAD

**Issue by thang2162** [m0dch3n/vue-cli-plugin-cordova#42]
I am getting error code 65 with the following commands with the system being unable to locate the xcarchive. 

 npm run cordova-serve-ios # Development IOS
 npm run cordova-build-ios # Build IOS

This is a known issue with cordova being incompatible with xcode's new build method and can be solved by build the cordova ios directly using: cordova run ios --buildFlag='UseModernBuildSystem=0' as a workaround.

A workaround to getting serve working on ios is to do the following: 

1. In index.js change:  

From:
  const getPlatformPathWWW = platform => {
    return api.resolve(`${cordovaPath}/platforms/${platform}/platform_www`)
  }

To:
 const getPlatformPathWWW = platform => {
    return api.resolve(`${cordovaPath}/www`)
  } 

2. Run: npm run cordova-serve-android

3. From cordova project root run: cordova build ios --buildFlag='UseModernBuildSystem=0'

4. Open ios project in xcode and run from scode.

5. Hot-Reload should be working on both ios and android

**Comment by m0dch3n** [comment]
for buildflag you can use build.json from cordova like some issues already mentioned here

https://github.com/m0dch3n/vue-cli-plugin-cordova/issues?utf8=✓&q=is%3Aissue+build.+json

**Comment by m0dch3n** [comment]
PS changing this line to www isn't correct, because then cordova.js etc will be missing I think

**Comment by thang2162** [comment]
It won't. I tested it out with on my MacBook Pro.

**Comment by m0dch3n** [comment]
ok, I'll give it try when I've some time

**Comment by m0dch3n** [comment]
> From:
> const getPlatformPathWWW = platform => {
> return api.resolve(`${cordovaPath}/platforms/${platform}/platform_www`)
> }
> 
> To:
> const getPlatformPathWWW = platform => {
> return api.resolve(`${cordovaPath}/www`)
> }

I had time, to try this, this is not working, because under `http://localhost:8080/cordova.js` the cordova.js is no longer served then...

I close now this ticket, because the rest are cordova specific problems, and not plugin related problems

Once cordova solves these Xcode 10 Build Problems, the plugin should work again without build.json etc...
