### ISSUE TITLE
Cordova-serve-android not workin

### ISSUE THREAD

**Issue by Diptyajit1994** [m0dch3n/vue-cli-plugin-cordova#53]
Hi, 
While i was building the app for android development environment the config file property <content src="index.html" /> in src-cordova changed to <content src="my loccal ip" />. The build was failing while i changed the config file to <content src="index.html" /> after this the android build doesnot fail and it is deployed to the android device but it does not contain the  basic cordova device ready ui not the vuetify uI

**Comment by m0dch3n** [comment]
Seems to be cordova related and not plugin. Did you try build manually without plugin, but with cordova commands in src-cordova? Also read the README if you have blank page etc, usually it's path related, where javascripts are not loaded...

There also some closed issues here already explaining more the problems, then in the README...

**Comment by Diptyajit1994** [comment]
I have user "cordova run android" in src-cordova and it provides the generic cordova index.html file not the vue coplied file

**Comment by m0dch3n** [comment]
build your app to src-cordova/www for this

**Comment by ponponner** [comment]
When installing or running scripts, the console worked well, but VueUI(on windows) did not.
It may be nice to say about it in the documentation.
