### ISSUE TITLE
content src in the config.xml does not change

### ISSUE THREAD

**Issue by inyourhands** [m0dch3n/vue-cli-plugin-cordova#54]
Hi.
When I first execute the command "npm run cordova-build-ios", the content src value in the cordova config.xml file looks like this:

```
<content src="index.html" />
```

But the second time i run the command "npm run cordova-serve-ios", it changes as follows.

```
<content src="http://192.168.219.109:8080" />
<allow-navigation href="http://192.168.219.109:8080" />
```

I think it's normal now.
However, I run the command "npm run cordova-build-ios" again after that, the above value will not be reset to the value shown below.

```
<content src="index.html" />
```

I think it should change to the original, but it does not.

Is it a bug?
Or did I misunderstand?
(please understand my poor english)

**Comment by m0dch3n** [comment]
well it's not a bug, that this changes during development, this is even documented in the README.

Basically in development, `npm run serve` is executed and `cordova run`, and the cordova webview is pointing to your dev server...

maybe your IDE or Linter or something else is touching the file too, so my regexp is not working:

https://github.com/m0dch3n/vue-cli-plugin-cordova/blob/adc8dd0221b992dae99e4e3192b098209f60c280/index.js#L109-L124

or the SIGTERM are note catched, to reset the file, when you kill the command:

https://github.com/m0dch3n/vue-cli-plugin-cordova/blob/adc8dd0221b992dae99e4e3192b098209f60c280/index.js#L176-L181

**Comment by inyourhands** [comment]
Thank you for explanation~

**Comment by inyourhands** [comment]
I suggest one thing.
I would like the `cordovaContent` function to be executed within the `runBuild` function.
This is because `dev server ip(http://192.168.219.109:8080)` does not change to `index.html` even when the `npm run cordova-serve-*` function is executed.

Or, would you be grateful if you could tell me the order of commands that `dev server ip(http://192.168.219.109:8080)` could change to `index.html` when I run the `npm run cordova-serve-*` command after changed `dev server ip(http://192.168.219.109:8080)`.

Thank you for your efforts and this project

**Comment by m0dch3n** [comment]
During runBuild it's not possible, runBuild is for production build, and runServe for development. A build should not point to a dev server... 

during serve, changeContent is executed to let cordova point to your dev server, and on a sigterm signal it's rollbacked... So if it does not rollback to index.html, please check, why the sigterm is not catched in your case. Maybe you (or your IDE) are not correctly stopping the serve command...

**Comment by inyourhands** [comment]
You mean that `dev server ip(http://192.168.219.109:8080)` rollback automatically when `npm run cordova-serve-*` command stops?

Well... i'm using Vue-CLI-GUI tool and VSCode.
I will check again what went wrong.

I'm sorry to bother you & thank you~ ^_________^*

**Comment by m0dch3n** [comment]
yeah, exactly, if SIGINT or SIGTERM are thrown, the config is reverted to index.html

**Comment by m0dch3n** [comment]
line 176-181 as on my first post here

**Comment by ponponner** [comment]
In Production mode, Why doesn't `runBuild` call `cordovaContent` to pointing the cordova config.xml to index.html ?

**Comment by ponponner** [comment]
It worked well with the console, but it did not work well with VueUI.

**Comment by ponponner** [comment]
When installing or running scripts, the console worked well, but VueUI(on windows) did not.
It may be nice to say about it in the documentation.
