### ISSUE TITLE
Uncaught SyntaxError: Use of const in strict mode on Android <7.0

### ISSUE THREAD

**Issue by kroegen** [m0dch3n/vue-cli-plugin-cordova#55]
Steps to reproduce:
- Take a phone with Android <7.0
- npm run cordova-serve-android
- You will see blank screen with message "Uncaught SyntaxError: Use of const in strict mode" in debug console

**Comment by m0dch3n** [comment]
Does this happen with standard vue app? 

Or is your app already modified ? Are others plugins like vuetify added i.e ? 

The standard vuejs should be compatible with android <7.0. However vuetify i.e is not and you need polyfill...

Take a look i.e. https://github.com/m0dch3n/vue-cli-plugin-cordova/issues/37

**Comment by m0dch3n** [comment]
https://github.com/vuejs-templates/webpack/issues/1253

**Comment by kroegen** [comment]
> Does this happen with standard vue app?
> 
> Or is your app already modified ? Are others plugins like vuetify added i.e ?
> 
> The standard vuejs should be compatible with android <7.0. However vuetify i.e is not and you need polyfill...
> 
> Take a look i.e. #37

I just checked with standard vue app and everything worked
No, I didn't use vuetify or other plugins, but now I see where to go next
It should be something with some of dependencies

**Comment by m0dch3n** [comment]
I guess you need to polyfill or babelify some of your modifications, good luck!
