### ISSUE TITLE
Some way to change app name/title.

### ISSUE THREAD

**Issue by SzateX** [m0dch3n/vue-cli-plugin-cordova#56]
Hi. I have some question. Is any way to change generated app name? If I manually change <name> in config.xml after build cli changes name to default.

**Comment by m0dch3n** [comment]
I did not test, but are you sure, that this happens? Which IDE are you using? I.e I'm using Webstorm, and when I change a file externally, and then immediately afterwards in the IDE, without refreshing it before, webstorm has still the cached version in memory and detects that the file was changed externally.

It asks then, if I want to keep the memory changes, the external changes, or view the differences...
