### ISSUE TITLE
How to add --buildFlag='-UseModernBuildSystem=0'

### ISSUE THREAD

**Issue by ZhongkaiChen** [m0dch3n/vue-cli-plugin-cordova#57]
I find your plugin very helpful since it can realise hot reloading. 
Nevertheless, it didn't work for ios devices since cordova is not compatible with the new building system. 
Is it possible to add  '-UseModernBuildSystem=0'

**Comment by pynner** [comment]
Under src-cordova, I have a build.json that looks like this 

`{
  "ios"    : {
    "debug"  : {
      "buildFlag": [
        "-UseModernBuildSystem=0"
      ]
    },
    "release": {
      "buildFlag": [
        "-UseModernBuildSystem=0"
      ]
    }
  },
  "android": {
    "debug"  : {
    },
    "release": {
    }
  }
}
`

**Comment by m0dch3n** [comment]
the solution currently is to use build.json, this was already discussed in the issues here

https://github.com/m0dch3n/vue-cli-plugin-cordova/issues?utf8=%E2%9C%93&q=is%3Aissue+buildFlag
