### ISSUE TITLE
Use https instead of http in serve

### ISSUE THREAD

**Issue by Allakazan** [m0dch3n/vue-cli-plugin-cordova#64]
I need to serve the vue app in https to access cordova plugins, such as geolocalization.

I put this json inside vue.config.js:
devServer: { https: true }

And it worked, Vue are serving with https.

But this vue plugin keeps the http url on config.xml file, how i can serve the app in https ?

**Comment by m0dch3n** [comment]
https://github.com/m0dch3n/vue-cli-plugin-cordova/commit/c8136d605cc5149cd35fc17b7c3409dc5dd56a85

this has already been fixed, please update your plugin version

**Comment by m0dch3n** [comment]
https://github.com/m0dch3n/vue-cli-plugin-cordova/pull/58

**Comment by Allakazan** [comment]
Thanks :smile: :+1:

**Comment by Allakazan** [comment]
Worked as well in the latest version
