### ISSUE TITLE
assets-only build

### ISSUE THREAD

**Issue by jacobg** [m0dch3n/vue-cli-plugin-cordova#65]
In development, I frequently just update a web asset, and want to re-run it simulator or on a device. But to run complete build `npm run cordova-build-{platform}` takes a while. It would be great to have a quick build of just webpack assets, and copy them to `src-cordova/www`. Then I can just run Xcode IDE build, which seems to be faster than running command line xcodebuild.

**Comment by m0dch3n** [comment]
https://github.com/m0dch3n/vue-cli-plugin-cordova/pull/41

I think this is what you are searching for or not ?

**Comment by jacobg** [comment]
I don't think so. That runs cordova prepare. I just want to copy in new web assets into each platform.

**Comment by m0dch3n** [comment]
ok, in this case, feel free, to create a PR with the specific commands, maybe with something like `cordova-build-www-{platform}`

**Comment by m0dch3n** [comment]
Hey, should I close this issue, or are gonna create a PR for this ?

**Comment by jacobg** [comment]
I'm planning to create a PR. I just haven't gotten to it yet.

**Comment by m0dch3n** [comment]
ok, nP, thanks!

**Comment by m0dch3n** [comment]
Hi @jacobg

I implemented your build only www by myself now in v2.3.1

PS: if you upgrade, you need to adapt your config.xml too: Just add `<hook type="after_prepare" src="../node_modules/vue-cli-plugin-cordova/serve-config-hook.js" />``

Otherwise the plugin is no longer pointing the config.xml to the dev server...

**Comment by jacobg** [comment]
@m0dch3n Awesome, thank you so much!
