### ISSUE TITLE
Android shows white screen and nothing more

### ISSUE THREAD

**Issue by navicstein** [m0dch3n/vue-cli-plugin-cordova#68]
Android shows white screen and nothing more, when i run `npm run cordova-serve-android` it serves and initializes on my phone but nothing is shown on my device, but it behaves very well on browser

**Comment by m0dch3n** [comment]
which android version do you use? below 4.4 chances are high, that your webview (android inline browser) does not support all the javascript features like es6 etc... in this case you need to polyfill and or babelify your project... (which is by far out of support I can give on this issue tracker)

**Comment by m0dch3n** [comment]
Try your app on android 7 or 8, if it works there, you need to make your app compatible to older browsers & androids...

**Comment by navicstein** [comment]
Yeah, that was the problem, i used an newer version of android and it worked as expected, i forgot that i commented out `import "@babel/polyfill"` from my `main.js` because of some conflicting issues with `core-js` (i was using `pnpm` instead of `npm`) and i also added    `"not dead", "android 4.4.3-4.4.4"` to my browserlist config
 -  keep doing the thing :) thanks a lot :smile:
