### ISSUE TITLE
cordova-serve-ios switches to safari on launch

### ISSUE THREAD

**Issue by mulhoon** [m0dch3n/vue-cli-plugin-cordova#7]
Great plugin.  Thanks for your work 😃

`cordova-serve-ios` opens on my iPhone (6), but as soon as the app opens, it switches over to safari and loads the ip to my local machine. Do you know why it doesn't stay within the app?

Thanks
N

**Comment by m0dch3n** [comment]
Unfortunately, I don't own an iPhone, so I can't tell you...

But I think, this is more cordova related

**Comment by m0dch3n** [comment]
Or maybe, for ios, we should'nt point config.xml to the dev ip, but use an index.html with an iframe...

I'll take a look at this problem, in 2 weeks

**Comment by m0dch3n** [comment]
In the meantime, you can try this

https://stackoverflow.com/questions/45419719/cordova-opens-startpage-in-safari-instead-of-in-the-app

**Comment by mulhoon** [comment]
@m0dch3n Thanks, this worked.
This will speed up dev. But I'd assume, like you said, it won't work in build as it's a serious security concern - opening an app that loads from a remote server.

Thanks
N

**Comment by m0dch3n** [comment]
Can ypu please try release 2.0.2, if this works better now?
