### ISSUE TITLE
ERR_CLEARTEXT_NOT_PERMITTED with android 9

### ISSUE THREAD

**Issue by syonip** [m0dch3n/vue-cli-plugin-cordova#72]
Hi,
Getting this error when using `yarn cordova-serve-android`
It seems that android 9 disables cleartext by default.
The solution suggested here works: https://stackoverflow.com/questions/54752716/why-am-i-seeing-neterr-cleartext-not-permitted-errors-after-upgrading-to-cordo

Happy to create a PR if you agree with the implementation.

**Comment by ssendev** [comment]
putting
```js
devServer: {
    https: true,
}
```
in `vue.config.js` works too

i actually have
```js
devServer: {
    host: 'localhost',
    public: 'localhost:8080',
    port: 8080,
    https: true,
}
```
in there and `"serve-android": "adb -d reverse tcp:8080 tcp:8080 && vue-cli-service cordova-serve-android"` in `package.json` to avoid having a publicly accessible dev server running. at least for android and browser. googling around shows that it is at least theoretically also possible for ios but is a lot more involved

**Comment by syonip** [comment]
Thanks, setting: 
```
devServer: {
    https: true,
}
```
 does work well for android.

Maybe this should be the default mode for the plugin somehow, as it doesn't function without it?

**Comment by m0dch3n** [comment]
when I developped the plugin (before cordova 8.0), it was the inverse problem, that serving over https did not work. 

But I think we can now switch to https, knowing, that if the app will contact any external api server over http will no longer work then...

**Comment by syonip** [comment]
Thanks :)

**Comment by ssendev** [comment]
@m0dch3n  `options.devServer.https || true` is always true

**Comment by m0dch3n** [comment]
> @m0dch3n `options.devServer.https || true` is always true

Thx 🙈 I fixed this now...
