### ISSUE TITLE
ERR CACHE MISS

### ISSUE THREAD

**Issue by Symorp** [m0dch3n/vue-cli-plugin-cordova#77]
Hello,
I am getting this error when I run `npm run cordova-serve-android`, It is opening as alert with text:
`net::ERR_CACHE_MISS (here is ip of my computer)`

Can you please help me how to run my vue app with this plugin. Many thanks all

**Comment by m0dch3n** [comment]
seems like a cordova permission problem, which are out of support of this issue tracker... so I will not further investegate and or help you more.

sorry, but I don't have the time

ttps://stackoverflow.com/questions/40060800/cordova-neterr-cache-miss

btw this was the first hit, on google, by searching 

`net::ERR_CACHE_MISS`
