### ISSUE TITLE
white blank screen on device emulators and browser: "page not working"

### ISSUE THREAD

**Issue by joeSaad** [m0dch3n/vue-cli-plugin-cordova#78]
I have tried following those steps a number of times. 
```
$ vue create my-app
$ cd my-app
$ vue add cordova
$ npm run cordova-prepare
$ npm run cordova-serve-ios
```

Just to find a blank screen on simulator and my browser on port 8080 "page not working" 

Any advice? 

Thanks

**Comment by m0dch3n** [comment]
usually a blank page, means your javascript is not booting vue at all

this comes often, when you have an old javascript engine, not supporting es6 or other new features...

so try a newer android version, 7 or more, first

if it's still not working, go to remote devices in chrome, connect to the android cordova webview and check the error
