### ISSUE TITLE
use cordova-serve-android on the real phone is showing white screen when app is started

### ISSUE THREAD

**Issue by woshiwangshuang** [m0dch3n/vue-cli-plugin-cordova#80]

**Comment by m0dch3n** [comment]
https://github.com/m0dch3n/vue-cli-plugin-cordova/issues/78

**Comment by woshiwangshuang** [comment]
I have add polyfill，and I copy the generated dist catalog of vue-cli build to www catalog  of src-cordova，and use cordova-run-android，its worked on real device（8.0），but I use cordova-serve-android，its not work.

**Comment by m0dch3n** [comment]
as said in the other issue, connect to the webview with remote devices and check in the console the error

I think you can solve your problems with the right polyfills and or by babelfying (webpacking) your project correctly, to work on any javascript engine...
