### ISSUE TITLE
about:blank on ios device

### ISSUE THREAD

**Issue by tartinesKiller** [m0dch3n/vue-cli-plugin-cordova#84]
Device is an iPhone 5s, running ios 12.3.1
Cordova 9.0.0 (cordova-lib@9.0.1)
Occured on an existing project, so I tried on a brand new project by doing
```
vue create test
cd test
vue add cordova
```
When running script cordova-serve-ios, no build errors or whatsoever, the app starts on the device, then nothing, just a blank screen. Looking in the devtools of Safari reveal no errors at all, and the document is empty (only html and body tags, with no attribute).
Running in an emulator gives the same behaviour.
However, if I build the app for production mode, it just works fine. 
Browser platform is running fine too. 
It seems like the debug html isn't being copied properly in the ios app
I will try to investigate further, I can provide any additional informations if needed

Thanks in advance.

**Comment by tartinesKiller** [comment]
Seems like that indeed, device is on the same network, dev server is running (I can access the app with Safari on the device)
You mean the config.xml in src-cordova/www?

**Comment by tartinesKiller** [comment]
Thanks for your help anyway, if I manage to fix it I'll update the issue, if anybody encounter the same error 
Thanks again

**Comment by m0dch3n** [comment]
thx
