### ISSUE TITLE
Add support for cordova installed as a dev dependency

### ISSUE THREAD

**Issue by AssetKid** [m0dch3n/vue-cli-plugin-cordova#87]
Hello,

At the moment, `Cordova` has to be installed globally for the generator to work

https://github.com/m0dch3n/vue-cli-plugin-cordova/blob/master/generator.js#L8-L13

It is not always possible to install packages globally due to permission restrictions. Is it possible to support `Cordova` installed as a dev dependencies?

Useful Links

* [Introducing npx: an npm package runner](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b)
* [npm `v5.2.0 (2017-07-05)`](https://github.com/npm/npm/releases/tag/v5.2.0) 
* Node.js `8.2.0` (upgrade npm to 5.3.0) - https://github.com/nodejs/node/pull/14235

**Comment by m0dch3n** [comment]
@AssetKid feel free to create PR, I'll merge it then

**Comment by AssetKid** [comment]
I forgot I opened this. I did attempt to make a PR but the solution was not elegant. The cwd (i.e. src-cordova) for the `cordova` commands and the local dependencies install location (project root) are different.

This means `npx cordova` commands won't work.

I did have to hard code certain paths in the project I was working on but it was not an elegant solution. I'll close this now.
