### ISSUE TITLE
Use yarn instead of npm

### ISSUE THREAD

**Issue by am** [m0dch3n/vue-cli-plugin-cordova#9]
Is there any particular reason to use `npm` instead of `yarn`? @vuejs [AFAIK](https://github.com/vuejs/vue/blob/dev/yarn.lock) use yarn to manage their projects. I think there are a few benefits, just curious to know what are your thoughts.

(I could take care of migrating to `yarn` if you will)

**Comment by m0dch3n** [comment]
no, there is no particular reason, I'm simply not used to yarn, but maybe it's time to do this, so if you want, go ahead! And thanks!

**Comment by eladcandroid** [comment]
I don't think there's a still good reason to use Yarn today

**Comment by m0dch3n** [comment]
Hmmm, as I don't have experience with yarn, I think, it's better, if we stick to npm... 

It seems, yarn was better, but now npm has same important features... 

https://iamturns.com/yarn-vs-npm-2018/

https://blog.risingstack.com/yarn-vs-npm-node-js-package-managers/

My personal opinion is, I don't like to install million of different special tools, if the basic tool, does everything I need,and the other ones are only more fancy...

**Comment by m0dch3n** [comment]
PS yarn also works with package-lock.json, so yarn users are free to still use yarn... 

https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/

**Comment by am** [comment]
> yarn also works with package-lock.json

This is a good thing I wasn't aware of. Nevertheless this is only good for trying out the tool, since: 

> We highly recommend you to delete the package-lock.json file if you decide to use yarn in order to avoid future confusion and possible consistency issues.

---

> I don't like to install million of different special tools, if the basic tool, does everything I need

Agreed on that one, now a few facts you can also test:

## npm (6.4.1)

1. first npm install (without lock)
	```
	» rm -rf node_modules package-lock.json yarn-error.log yarn.lock && time npm i
	npm notice created a lockfile as package-lock.json. You should commit this file.
	added 413 packages from 307 contributors and audited 1499 packages in 5.794s
	found 0 vulnerabilities
	
	npm i  8.74s user 2.61s system 180% cpu 6.283 total
	```
2. first npm install (with lock)
	```
	» rm -rf node_modules && time npm i
	added 413 packages from 307 contributors and audited 1499 packages in 5.064s
	found 0 vulnerabilities
	
	npm i  7.79s user 2.50s system 187% cpu 5.498 total
	```
3. npm install
	```
	» time npm i
	audited 1499 packages in 2.832s
	found 0 vulnerabilities
	
	npm i  2.46s user 0.29s system 84% cpu 3.255 total
	```

## yarn (1.9.4)

1. first yarn install (without lock)
	```
	» rm -rf node_modules package-lock.json yarn.lock && time yarn
	yarn install v1.9.4
	info No lockfile found.
	[1/4] 🔍  Resolving packages...
	[2/4] 🚚  Fetching packages...
	[3/4] 🔗  Linking dependencies...
	[4/4] 📃  Building fresh packages...
	
	success Saved lockfile.
	✨  Done in 4.86s.
	yarn  3.13s user 2.71s system 112% cpu 5.173 total
	```

2. first yarn install (with lock)
	```
	» rm -rf node_modules && time yarn
	yarn install v1.9.4
	[1/4] 🔍  Resolving packages...
	[2/4] 🚚  Fetching packages...
	[3/4] 🔗  Linking dependencies...
	[4/4] 📃  Building fresh packages...
	
	✨  Done in 2.43s.
	yarn  2.20s user 2.57s system 174% cpu 2.733 total
	```
3. yarn install
	```
	» time yarn
	yarn install v1.9.4
	[1/4] 🔍  Resolving packages...
	success Already up-to-date.
	✨  Done in 0.26s.
	yarn  0.61s user 0.07s system 115% cpu 0.579 total
	```

## comparison

| speed | fresh | lock  | consequent |
|-------|-------|-------|------------|
| npm   | 6.283 | 5.498 | 3.255      |
| yarn  | 5.173 | 2.733 | 0.579      |

> I ran this three times, and speeds were pretty much the same.

I don't agree. I can tell from experience (we run in production both npm and yarn, on the same project! It's a monorepo where cordova is isolated) that yarn still runs faster by far, this is the main reason we use yarn, it reduces the build times.

### conclusions

This is a very small project, and it won't impede users from using yarn on their end (since they won't be developing over this project directly), as matter of fact @vuejs uses yarn internally and most of the documentation points out to `yarn` command as well of `npm`. 
By the end of the day is up to the maintainers of the project if they want to shave time or not. IMO yarn still beats npm in many other things (blog post need here), hopefully this will change one day.

That said, another important topic is that `cordova-fetch` is tied to npm (if you want to have a good read about it https://issues.apache.org/jira/browse/CB-12242). In the project I'm currently working, this was the main reason to keep the cordova project isolated under the application project, it's very similar how this plugin works, that places the cordova under it's own dir. Although this doesn't affect the decision at the plugin level I think its an important note to add.

**Comment by m0dch3n** [comment]
@am thanks for this introduction to yarn and your experience in production. 

We never had such big projects, that we were pissed off with npm... 

So I can't be against yarn, as I simply don't have a lot experience with it. 

As you said, this project is so small, that the differences are minimal! so it doesn't really matter if you use yarn or npm and yarn is compatible with package-lock.json

Nevertheless,I think, I need to try more yarn in the future :)
