### ISSUE TITLE
ios simulator blank

### ISSUE THREAD

**Issue by yokins** [m0dch3n/vue-cli-plugin-cordova#90]
# environments
```
system: macOS Mojave
ios simulator: iPhone Xʀ iOS 12.4
vue-cli-plugin-cordova: ^2.3.6
vue: ^2.6.10
```
# bug description
i create an new vue project，add plugin and run `yarn cordova-serve-ios` success。but the ios simulator display a blank screen,  there is no error message，bug open the localhost url by ip in browser，find  `SEC_ERROR_UNKNOWN_ISSUER` code.

# screenshots
![image](https://user-images.githubusercontent.com/45431050/68276672-72474300-00a8-11ea-99f1-02695b77f9cc.png)

![image](https://user-images.githubusercontent.com/45431050/68276593-4f1c9380-00a8-11ea-884b-774c2039bd01.png)

**Comment by m0dch3n** [comment]
https://github.com/m0dch3n/vue-cli-plugin-cordova/issues?utf8=%E2%9C%93&q=is%3Aissue+blank

have tried the solutions in the others issues?

**Comment by yokins** [comment]
thank you, i fond the solution with #85

**Comment by tripflex** [comment]
I personally had to add this for iOS to be able to connect to my local IP address as it was throwing SSL errors in Safari dev console without it

https://stackoverflow.com/a/34808112/378506

**Comment by m0dch3n** [comment]
I don't have these SSL problems, as I'm accessing my dev server through a proxy which wraps https with  .dev domain and a valid cert from letsencrypt
