### ISSUE TITLE
Clean failing when running on iOS

### ISSUE THREAD

**Issue by daviesdoclc** [m0dch3n/vue-cli-plugin-cordova#92]
I'm seeing the following error when running 'npm run cordova-serve-ios'
```
Running command: xcodebuild -project Digby.xcodeproj -configuration Debug -alltargets clean
note: Using new build system
error: Could not delete `/Users/daviesd/workspace/mobile/digby/src-cordova/platforms/ios/build` because it was not created by the build system.

** CLEAN FAILED **

```
I'm running Xcode 11.2.1.  I just started using this plugin today, so I might just be unfamiliar with it.  Please advise.

**Comment by m0dch3n** [comment]
https://stackoverflow.com/questions/52732824/multiple-errors-after-migrating-to-xcode-10

this is xcode related I think...

**Comment by m0dch3n** [comment]
btw I'm ignoring the message...

**Comment by daviesdoclc** [comment]
Ok. I'll close and monitor the Xcode issue. Thanks.

**Comment by m0dch3n** [comment]
maybe you find also some advices in the cordova documentation also... In fact, I never investigated into this in more detail, because it never stopped me, to build my app...

**Comment by m0dch3n** [comment]
https://jira.appcelerator.org/browse/TIMOB-26110 also some information, anyway, as I said, I'm simply ignoring the message currently...
