### ISSUE TITLE
Can't get non-default browser to work in devServer

### ISSUE THREAD

**Issue by daviesdoclc** [m0dch3n/vue-cli-plugin-cordova#93]
I'm trying to get cordova-serve-browser to open the non-default browser.  I want "Google Chrome".  I've tried adding
```
"devServer": {
    "open": "Google Chrome"
  }
```
per webpack instructions, but it's not working.  Is there an alternative for vue-cli-plugin-cordova?

**Comment by m0dch3n** [comment]
After 2 minutes of research, I found this

https://github.com/vuejs/vue-cli/issues/2141

So maybe it's not possible...

Does 
```
"devServer": {
    "open": "Google Chrome"
  }
```
work, when you run `npm run serve`

**Comment by daviesdoclc** [comment]
Good point. No, it's not working there either. Ok, sorry. I'll close.

**Comment by daviesdoclc** [comment]
I found out that vue-cli requires an environment variable called BROWSER.
https://github.com/vuejs/vue-cli/issues/2141#issuecomment-559143578
