### ISSUE TITLE
are there any conflicts with vue-cli 4 ? does it work with it ?

### ISSUE THREAD

**Issue by vesper8** [m0dch3n/vue-cli-plugin-cordova#94]
I've switched all my projects to vue-cli 4, not expecting that this might cause a problem with this plugin. I haven't yet deployed my hybrid apps to the app store but it's my plan to do so soon and I am wondering now if this plugin will still accomplish its work now that my projects are using vue-cli 4

Has anyone tried this? Is it possible that it works just fine in which case a new release should be made and the Readme should indicate that it supports both vue-cli 3 and 4 ?

Would appreciate some confirmation!

Thanks!

**Comment by danielhuggins** [comment]
I have tried this and it works fine as far as i can tell.

**Comment by m0dch3n** [comment]
I think we can close this issue then
