### ISSUE TITLE
Force serve on HTTP instead of HTTPS

### ISSUE THREAD

**Issue by Keftaa** [m0dch3n/vue-cli-plugin-cordova#95]
Hi,

When running `npm run cordova-serve-android` it only runs over HTTPS. I need to serve over HTTP. How can I achieve this?

**Comment by m0dch3n** [comment]
https://cli.vuejs.org/config/#devserver

**Comment by vesper8** [comment]
I added this so that for everything except IOS it uses https, which is the default, and for IOS only it uses http since that's what was needed for it to work

inside vue.config.js
```
  devServer: {
    https: !process.env.npm_lifecycle_event.includes('ios'),
  },
```
