### ISSUE TITLE
build targets are cleaning all platforms

### ISSUE THREAD

**Issue by daviesdoclc** [m0dch3n/vue-cli-plugin-cordova#98]
How come when I run

`cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-android`

I see

`Running command: xcodebuild -project Digby.xcodeproj -configuration Debug -alltargets clean
`

Is the platform not being passed to the "cordova clean" process?  Shouldn't platform be passed to cordovaClean and used in the spawn?

Update: I changed the code to pass it in and use it in the spawn and each target cleans properly now.  Would you like me to submit a patch or can you just make the change?

**Comment by m0dch3n** [comment]
yeah, thanks!

Just create a pull request! I'll merge it then

**Comment by daviesdoclc** [comment]
https://github.com/m0dch3n/vue-cli-plugin-cordova/pull/99
thanks!
